
# ENCODERS_SETUP
# https://docs.qmk.fm/features/encoders#encoders
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

# OLED_SETUP
OLED_ENABLE = yes
OLED_DRIVER = ssd1306
OLED_TRANSPORT = i2c
LTO_ENABLE = yes


# AUDIO_SETUP
AUDIO_ENABLE = no
AUDIO_DRIVER = pwm_hardware


TAP_DANCE_ENABLE = yes

CONSOLE_ENABLE = yes

LEADER_ENABLE = yes

DYNAMIC_MACRO_ENABLE = yes

DYNAMIC_TAPPING_TERM_ENABLE = yes

CAPS_WORD_ENABLE = yes
