#!/usr/bin/env -S uv run --script
#
# /// script
# requires-python = ">=3.13"
# dependencies = ["hidapi"]
# ///
import hid

# Define a list of device params, for which we must connect
# vid = 0xf1f1
# pid = 0x0315
vid = 0x5784
pid = 0x0001
usage_page = 0xff60
usage_id = 0x61


# for device in hid.enumerate():
#     if device['vendor_id'] == vid and device['product_id'] == pid:
#         print(device)

keyboard = None
for device in hid.enumerate():
    print(device)
    # if device['vendor_id'] == vid and device['product_id'] == pid and device['usage_page'] == usage_page and device['usage'] == usage_id:
    if device['vendor_id'] == vid and device['product_id'] == pid :
        print(f"Opening keyboard: {device['path']}")
        keyboard = hid.device(path=device['path'])
        break

if keyboard is None:
    print("Keyboard not found")
    exit(1)


# to_send = pad_message(b'1')
# print(f"To send : {to_send}")
byte_array = bytearray()
byte_array.append(0)
byte_array.append(10)
byte_array.append(0)
keyboard.write(bytes(byte_array))
keyboard.close()
